apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        ports:
        - containerPort: 5672
        - containerPort: 15672 # Management interface port
        volumeMounts:
        - name: rabbit-secrets
          mountPath: /etc/secrets
        - name: startup-script
          mountPath: /scripts
        command: ["/bin/bash", "/scripts/startup.sh"]
      volumes:
      - name: rabbit-secrets
        secret:
          secretName: rabbitmq-secret
      - name: startup-script
        configMap:
          name: rabbitmq-startup-script
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbitmq
  ports:
    - port: 5672
      targetPort: 5672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-maintenance
spec:
  type: NodePort
  selector:
    app: rabbitmq
  ports:
    - protocol: TCP
      port: 15672
      targetPort: 15672